# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:11.14.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/semaphore/semaphorejs

    steps:
      - checkout:
          path: ~/semaphore

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1.4-dependencies-{{ checksum "build/" }}
            - v1.4-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1.3-dependencies-

      - run: npm install

      - save_cache:
          paths:
            #- node_modules
            - semaphorejs/build/circuit.json
            - semaphorejs/build/proving_key.bin
            - semaphorejs/build/proving_key.json
            - semaphorejs/build/verification_key.json
            - semaphorejs/build/verifier.sol
          key: v1.4-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          name: end-to-end
          command: cd scripts && ./ci.sh
          no_output_timeout: 600m

      - store_artifacts:
          path: ~/semaphore/semaphorejs/build

